"""Local TLS collection; no live cluster and no independently observed workload."""
import copy
from dataclasses import replace
from datetime import datetime, timezone
import hashlib
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
from pathlib import Path
import ssl
import subprocess
import sys
import threading

import pytest

from dimaggi_receiver.kubernetes_collect import Collector, CollectorConfig
from dimaggi_receiver.kubernetes_import import import_kubernetes
from dimaggi_receiver.observations import ObservationError, ObservationStore
from test_kubernetes_import import bundle, intent, identity, COLLECTOR, T2

NOW = datetime(2026, 9, 19, 12, 0, 2, tzinfo=timezone.utc)


@pytest.fixture(scope="module")
def tls_material(tmp_path_factory):
    directory = tmp_path_factory.mktemp("collector-tls")
    certificate, key = directory / "cert.pem", directory / "key.pem"
    subprocess.run(["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-keyout", str(key),
                    "-out", str(certificate), "-days", "1", "-subj", "/CN=localhost",
                    "-addext", "subjectAltName=DNS:localhost,IP:127.0.0.1"],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    return certificate, key


@pytest.fixture
def lab(tmp_path, tls_material):
    certificate, key = tls_material
    resources = {"job": bundle()["job"], "pods": {"apiVersion": "v1", "kind": "PodList",
        "metadata": {"resourceVersion": "list-1"}, "items": bundle()["pods"]},
        "namespace": {"apiVersion": "v1", "kind": "Namespace", "metadata": {"name": "synthetic-lab", "uid": "namespace-uid-1"}}}
    resources["job"]["metadata"]["resourceVersion"] = "job-version-1"
    calls = []

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *args):
            pass

        def do_GET(self):
            calls.append(self.path)
            assert self.headers["Authorization"] == "Bearer TEST-COLLECTOR-CREDENTIAL"
            name = "log" if "/log?" in self.path else "pod" if "/pods/" in self.path else "pods" if "/pods?" in self.path else "job" if "/jobs/" in self.path else "namespace"
            status = resources.get(name + "_http_status", resources.get("http_status", 200))
            raw = resources.get("raw", resources[name] if isinstance(resources[name], bytes) else json.dumps(resources[name]).encode())
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)
            if name == "job" and resources.get("change_job"):
                resources["job"]["metadata"]["resourceVersion"] = "changed-version"

    peer = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certificate, key)
    peer.socket = context.wrap_socket(peer.socket, server_side=True)
    thread = threading.Thread(target=peer.serve_forever, daemon=True)
    thread.start()
    verifier = tmp_path / "verifier"
    # Explicit trusted test double tests the collector boundary. Separate integration
    # tests run the real source-pinned Go verifier against upstream-generated bytes.
    verifier.write_text(f"#!{sys.executable}\n" + '''import hashlib,json,sys
from pathlib import Path
a=sys.argv
obj=Path(a[a.index('--object')+1]).read_bytes()
report=Path(a[a.index('--report')+1]).read_bytes()
r={'schema':'dimaggi-batch-object-match/v1','matched':True,'comparison_profile':a[a.index('--profile')+1],
'uid':a[a.index('--expected-uid')+1],'resource_version':a[a.index('--expected-resource-version')+1],
'object_digest':'sha256:'+hashlib.sha256(obj).hexdigest(),'report_digest':'sha256:'+hashlib.sha256(report).hexdigest(),
'execution_authorized':False,'dispatch_possible':False,'source_authenticated':False,'permission':'not_granted'}
print(json.dumps(r))
''')
    verifier.chmod(0o700)
    config = CollectorConfig(endpoint=f"https://127.0.0.1:{peer.server_port}", ca_pem=certificate.read_text(),
        bearer_token="TEST-COLLECTOR-CREDENTIAL", collector_id=COLLECTOR, source_epoch="epoch-1", target_id=intent()["target_id"], **identity(),
        verifier_path=str(verifier), verifier_digest="sha256:" + hashlib.sha256(verifier.read_bytes()).hexdigest(),
        valid_until_utc="2026-09-19T13:00:00Z")
    with ObservationStore(tmp_path / "observations.sqlite") as store:
        registered = intent()
        registered["evidence_class"] = "observed"
        for kind, source in registered["sources"].items():
            store.register_source(source, kind, registered["target_id"])
        store.register_intent(registered)
        planning = {"request_id": "request-1", "profile": registered["profile_id"], "cluster_id": config.cluster_id,
                    "namespace": config.namespace_name, "namespace_uid": config.namespace_uid}
        kwargs = {"request_id": "request-1", "intent_json": json.dumps(planning).encode(),
                  "report_json": json.dumps({"report_id": registered["report_id"]}).encode()}
        yield config, resources, calls, store, kwargs
    peer.shutdown()
    peer.server_close()
    thread.join()


def collect(lab, config=None, clock=lambda: NOW):
    c, _, _, store, kwargs = lab
    return Collector(config or c, clock=clock).collect(store, **kwargs)


def test_tls_collection_appends_attributed_but_not_proven_completion(lab):
    result = collect(lab)
    assert result["state"] == "unknown" and result["evidence_class"] == "observed"
    assert not result["execution_proven"] and not result["dispatch_possible"]
    events = lab[3].history("request-1")
    payload = events[0]["event"]["payload"]
    assert payload["collection"]["source_authenticated"] is True
    assert payload["collection"]["pod_spec_verified"] is False
    assert len(lab[2]) == 5 and all("watch" not in path for path in lab[2])
    collect(lab)
    assert [x["event"]["source_sequence"] for x in lab[3].history("request-1")] == [1, 2]
    assert "TEST-COLLECTOR-CREDENTIAL" not in json.dumps(lab[3].history("request-1"))


@pytest.mark.parametrize("change", ["foreign_namespace", "foreign_job", "foreign_pod", "incomplete", "bool_remaining", "too_many", "changing_job", "redirect", "missing", "oversize", "duplicate_keys", "null_metadata"])
def test_refused_collection_makes_no_application_append(lab, change):
    _, resources, _, store, _ = lab
    if change == "foreign_namespace": resources["namespace"]["metadata"]["uid"] = "foreign"
    elif change == "foreign_job": resources["job"]["metadata"]["uid"] = "foreign"
    elif change == "foreign_pod": resources["pods"]["items"][0]["metadata"]["ownerReferences"][0]["uid"] = "foreign"
    elif change == "incomplete": resources["pods"]["metadata"]["continue"] = "next"
    elif change == "bool_remaining": resources["pods"]["metadata"]["remainingItemCount"] = False
    elif change == "too_many": resources["pods"]["items"] *= 1001
    elif change == "changing_job": resources["change_job"] = True
    elif change == "redirect": resources["http_status"] = 302
    elif change == "missing": resources["http_status"] = 404
    elif change == "oversize": resources["raw"] = b" " * ((1 << 20) + 1)
    elif change == "duplicate_keys": resources["raw"] = b'{"kind":"Job","kind":"Pod"}'
    elif change == "null_metadata": resources["namespace"]["metadata"] = None
    with pytest.raises(ObservationError): collect(lab)
    assert store.history("request-1") == []


@pytest.mark.parametrize("change", ["credential", "url", "profile", "expired", "verifier", "clock", "trust"])
def test_configuration_and_trust_refuse(lab, change):
    config = lab[0]
    if change == "credential": config = replace(config, bearer_token="bad\nheader")
    elif change == "url": config = replace(config, endpoint=config.endpoint + "/foreign")
    elif change == "profile": config = replace(config, profile="unknown")
    elif change == "expired": config = replace(config, valid_until_utc=T2)
    elif change == "verifier": config = replace(config, verifier_digest="sha256:" + "0" * 64)
    elif change == "trust": config = replace(config, ca_pem="not a CA")
    if change == "clock":
        collect(lab)
        with pytest.raises(ObservationError): collect(lab, clock=lambda: NOW.replace(second=1))
    else:
        with pytest.raises(ObservationError): collect(lab, config)
        assert lab[3].history("request-1") == []


def test_restart_epoch_and_configuration_lineage(lab):
    collect(lab)
    path = lab[3].path if hasattr(lab[3], "path") else None
    # A new collector instance recovers the source sequence from the durable
    # journal; no collector-local counter can reset it.
    collect(lab)
    changed = replace(lab[0], endpoint=lab[0].endpoint.replace("127.0.0.1", "localhost"))
    with pytest.raises(ObservationError): collect(lab, changed)
    collect(lab, replace(changed, source_epoch="epoch-2"))
    events = lab[3].history("request-1")
    assert [(x["event"]["source_epoch"], x["event"]["source_sequence"]) for x in events] == [("epoch-1", 1), ("epoch-1", 2), ("epoch-2", 1)]


def test_same_resource_version_with_changed_body_conflicts(lab):
    collect(lab)
    lab[1]["job"]["status"]["failed"] = 1
    with pytest.raises(ObservationError): collect(lab)
    assert len(lab[3].history("request-1")) == 1


def test_observed_json_cannot_enter_synthetic_import(lab):
    value = bundle()
    value["evidence_class"] = "observed"
    with pytest.raises(ObservationError):
        import_kubernetes(lab[3], json.dumps(value), request_id="request-1", expected_collector_id=COLLECTOR,
                          expected_identity=identity(), recorded_at_utc=T2)
    assert lab[3].history("request-1") == []


def test_config_and_collector_representations_redact_credentials(lab):
    assert "TEST-COLLECTOR-CREDENTIAL" not in repr(lab[0])
    assert "TEST-COLLECTOR-CREDENTIAL" not in repr(Collector(lab[0]))


@pytest.mark.parametrize("bound", ["MAX_HISTORY_BYTES", "MAX_HISTORY_EVENTS"])
def test_collector_refuses_full_history_without_reading_network_or_truncating(lab, monkeypatch, bound):
    import dimaggi_receiver.kubernetes_collect as module
    collect(lab)
    before = lab[3].history("request-1")
    calls = len(lab[2])
    monkeypatch.setattr(module, bound, 1)
    with pytest.raises(ObservationError, match="history limit"):
        collect(lab)
    assert lab[3].history("request-1") == before and len(lab[2]) == calls


def test_collector_refuses_append_beyond_full_history_byte_cap(lab, monkeypatch):
    import dimaggi_receiver.kubernetes_collect as module
    collect(lab)
    before = lab[3].history("request-1")
    calls = len(lab[2])
    stored_bytes = lab[3].db.execute(
        "SELECT SUM(LENGTH(CAST(body AS BLOB))) FROM events WHERE request_id=?",
        ("request-1",),
    ).fetchone()[0]
    # Existing history fits, so collection proceeds; the complete new event
    # cannot fit and must be refused before any durable append.
    monkeypatch.setattr(module, "MAX_HISTORY_BYTES", stored_bytes + 1)
    with pytest.raises(ObservationError, match="combined collection"):
        collect(lab)
    assert len(lab[2]) > calls
    assert lab[3].history("request-1") == before
